menu:
  Home: /
  Archives: /archives
  Demo: /mydemo

subnav:
  github: "https://github.com/cnzsb"
  weibo: "https://weibo.com/u/2821242461"
  mail: "mailto:cnzsb@foxmail.com"
  rss: "/atom.xml"

avatar: "/avatar.png"

# duoshuo comment
duoshuo: false
duoshuo_name:

# disqus comment
disqus: false
disqus_shortname:

# google analytics
googleTrackId: 'UA-71274501-1'
